<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>OmniRef.Core</RootNamespace>
    <AssemblyName>OmniRef.Core</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Raffinert.FuzzySharp" />
  </ItemGroup>
</Project>
